- UPGRADE.md
- src/Connection.php
| Is bugfix?    | no
| Breaks BC?    | yes
| Tests pass?   | no
The separate charset property is no longer needed. 
Both MySQL and PostgreSQL support setting charset via the dsn.
> Remove `$charset`

- src/Query.php
- tests/unit/CommandTest.php
- tests/unit/DatabaseTestCase.php
- tests/unit/QueryTest.php
- tests/unit/SchemaTest.php
Fix missing yii\db\Query object that cause no table use error in tests.
> Fix missing query constructor

- src/Constraints/CheckConstraint.php
- src/Constraints/Constraint.php
- src/Constraints/ConstraintFinderInterface.php
- src/Constraints/ConstraintFinderTrait.php
- src/Constraints/DefaultValueConstraint.php
- src/Constraints/ForeignKeyConstraint.php
- src/Constraints/IndexConstraint.php
- src/Schemas/Schema.php
- tests/AnyValue.php
- tests/SchemaTest.php
> Improve constraints classes.

- src/Connection/Connection.php
- src/Query/QueryBuilder.php
- src/Schema/ColumnSchemaBuilder.php
- src/Schema/Schema.php
- src/Schema/TableSchema.php
- tests/CommandTest.php
- tests/QueryBuilderTest.php
- tests/SchemaTest.php
> Improve schema classes.

- src/Exception/Exception.php
- src/Schema/Schema.php
Since that's what PDO uses and we're wrapping around it.
| Fixed issues  | https://github.com/yiisoft/yii2/issues/18203
> Use string as error code

- src/Connection/Connection.php
- src/Connection/ConnectionInterface.php
Example:
```php
/**
* Returns the name of the DB driver.
*
* @return string name of the DB driver
/
public function getDriverName(): string
{
return 'pgsql';
}
```
The tests will fail as I must add the method to each package.
> Adjust ConnectionInterface::class.

- src/Schema/Schema.php
| issue | https://github.com/yiisoft/db/issues/152
> Fix psalm issues.

- src/Connection/Connection.php
- src/Query/QueryBuilder.php
- src/Schema/Schema.php
- src/TestUtility/TestQueryBuilderTrait.php
- src/TestUtility/TestQueryTrait.php
- src/Transaction/Transaction.php
This fix is ​​required so that you can use QueryBuilder with databases that work without a PDO connection. Examples of such databases are Clickhouse and restream/reindexer
> Replace Connection to ConnectionInterface

- src/Command/Command.php
- src/Connection/Connection.php
- src/Connection/ConnectionInterface.php
- src/TestUtility/TestConnectionTrait.php
New boolean flag for `Connection`:
Ability to disable auto slave select for all read queries. Slave connection still can be used  with `$db->getSlave()` method
> Ability to disable auto slave select for all read queries

- .github/workflows/db-pgsql.yml
- src/QueryBuilder/DMLQueryBuilder.php
- tests/Provider/AbstractCommandProvider.php
> Normalize columns and values refactoring

- tests/Provider/ColumnTypes.php
https://github.com/yiisoft/yii2/pull/18500
This PR adds support for MySQL’s ANSI and ANSI_QUOTES modes, by checking for " characters in addition to ` whenever parsing the results of a SHOW CREATE TABLE command.
ANSI_QUOTES is enabled by default on DigitalOcean for MySQL 8, so it would be great to get this pulled in.
> Support for MySQL ANSI/ANSI_QUOTES modes

- CHANGELOG.md
- src/Schema/AbstractSchema.php
> Refactoring of `AbstractSchema::getColumnPhpType()` method

- docs/en/command/ddl.md
- src/QueryBuilder/DDLQueryBuilderInterface.php
| Fixed issues  | Fix some issues of phpdocs AND docs
> Fix phpdocs and docs

- CHANGELOG.md
- src/Connection/ConnectionInterface.php
> Minor fix phpdoc and changelog

- CHANGELOG.md
- src/Schema/Quoter.php
- tests/Db/Schema/QuoterTest.php
1. Added used function to `use function` block
2. Replaced `str_contains()` with `str_starts_with()`
3. Removed unnecessary chars from patterns of regular expression
4. Fixed bug of `quoteSql()` for sql containing table with prefix ([test](https://github.com/yiisoft/db/pull/756/files#diff-de323c8909d597344bdb19b9c5c9391c60b65ce9db9313642b76736deceb6aaaR98-R105))
5. Fixed bug of `getTableNameParts()` for cases with different quotes for tables and columns ([test](https://github.com/yiisoft/db/pull/756/files#diff-de323c8909d597344bdb19b9c5c9391c60b65ce9db9313642b76736deceb6aaaR91-R96))
6. Fixed bug of `quoteTableName()` for sub-query with alias ([test](https://github.com/yiisoft/db/pull/756/files#diff-de323c8909d597344bdb19b9c5c9391c60b65ce9db9313642b76736deceb6aaaR106-R112))
| Q …
> Refactor `Quoter`

- CHANGELOG.md
- src/Schema/TableSchemaInterface.php
See comment https://github.com/yiisoft/db-sqlite/pull/268#pullrequestreview-1564079720
> Deprecate compositeForeignKey()

- CHANGELOG.md
- src/Schema/SchemaInterface.php
`jsonb` is an incorrect abstract type. It is a specific `json` type of PorstgeSQL
See comment https://github.com/yiisoft/db/pull/723#discussion_r1254457912
**Repated PR:** yiisoft/db-pgsql#319
> Deprecate abstract type `SchemaInterface::TYPE_JSONB`

- CHANGELOG.md
- src/Query/Query.php
- src/Query/QueryPartsInterface.php
- src/QueryBuilder/AbstractDQLQueryBuilder.php
- tests/AbstractQueryBuilderTest.php
- tests/Common/CommonQueryTest.php
- tests/Provider/QueryBuilderProvider.php
1. Fix bug with Oracle when CTE aliases is not quoted.
2. Fix bug with Oracle and MSSQL: `RECURSIVE` expression is not needed for CTE.
* yiisoft/db-mssql#278
* yiisoft/db-oracle#240
* yiisoft/db-sqlite#274
* yiisoft/db-mysql#305
> Fix CTE query expressions

- src/Schema/QuoterInterface.php
Deprecate `$withColumn` argument of `Quoter::getTableNamesParts()` method
| Fixed issues  | #757
> Deprecate `$withColumn` argument of `Quoter::getTableNamesParts()`

- .github/workflows/active-record.yml
- .github/workflows/db-mariadb.yml
- .github/workflows/db-mssql.yml
- .github/workflows/db-mysql.yml
- .github/workflows/db-oracle.yml
- .github/workflows/db-pgsql.yml
- .github/workflows/db-sqlite.yml
- CHANGELOG.md
- src/Query/Query.php
- tests/AbstractQueryTest.php
> Fix query count

- CHANGELOG.md
- src/Command/AbstractCommand.php
- src/Driver/Pdo/AbstractPdoCommand.php
The optimization also removes extra call `$this->getRawSql()`.
> Deprecate unnecessary argument `$rawSql` of `AbstractCommand::internalExecute()`

- rector.php
> Fix rector

- CHANGELOG.md
- src/Constraint/ConstraintSchemaInterface.php
- src/QueryBuilder/AbstractDMLQueryBuilder.php
- src/Schema/AbstractSchema.php
> Specify result type of `ConstraintSchemaInterface::getTableIndexes()` method to `IndexConstraint[]`

- CHANGELOG.md
- src/Schema/AbstractSchema.php
> Refactor `AbstractSchema::getDataType()`

- CHANGELOG.md
- src/Command/AbstractCommand.php
- tests/Provider/CommandProvider.php
- tests/Support/Stringable.php
* Refactor `AbstractCommand::getRawSql()`
* Fix bug when value is `Stringable` object
| Fixed issues  | #783
> Refactor `AbstractCommand::getRawSql()`

- CHANGELOG.md
- src/Driver/Pdo/AbstractPdoCommand.php
- tests/Common/CommonPdoCommandTest.php
> Do not call `CommandInterface::getRawSql()` if no `logger` or `profiler`

- CHANGELOG.md
- src/QueryBuilder/AbstractDMLQueryBuilder.php
- tests/AbstractQueryBuilderTest.php
- tests/Db/QueryBuilder/QueryBuilderTest.php
- tests/Provider/QueryBuilderProvider.php
* yiisoft/db-mysql#313
* yiisoft/db-pgsql#326
* yiisoft/db-sqlite#283
* yiisoft/db-oracle#249
> Fix `QueryBuilderTest::testBatchInsert()`

- tests/Common/CommonCommandTest.php
* yiisoft/db-mssql#287
* yiisoft/db-oracle#250
* yiisoft/db-mysql#314
| Fixed issues  | #792
> Test `Command::insertWithReturningPks()` with empty values

- CHANGELOG.md
- src/Query/Query.php
- src/Query/QueryFunctionsInterface.php
> Add more specific psalm type for `QueryFunctionsInterface::count()` result

- tests/AbstractConnectionTest.php
| Is bugfix?        |❌
| New feature?  |❌
| Breaks BC?    |❌
| Fixed issues  | code readability increased
> return type of method is corrected.

- src/Query/Query.php
- src/Query/QueryInterface.php
- src/Query/QueryPartsInterface.php
- src/QueryBuilder/AbstractDQLQueryBuilder.php
- src/QueryBuilder/DQLQueryBuilderInterface.php
> Improve psalm types for scalar values in select

- CHANGELOG.md
- UPGRADE.md
- docs/guide/en/command/dml.md
- docs/guide/pt-BR/command/dml.md
- src/Command/AbstractCommand.php
- src/Command/CommandInterface.php
- src/Debug/CommandInterfaceProxy.php
- src/QueryBuilder/AbstractDMLQueryBuilder.php
- src/QueryBuilder/AbstractQueryBuilder.php
- src/QueryBuilder/DMLQueryBuilderInterface.php
- tests/AbstractQueryBuilderTest.php
- tests/Common/CommonCommandTest.php
- tests/Db/Command/CommandTest.php
- tests/Db/QueryBuilder/QueryBuilderTest.php
- tests/Provider/CommandProvider.php
- tests/Provider/QueryBuilderProvider.php
* Rename `batchInsert()` to `insertBatch()` in `DMLQueryBuilderInterface` and `CommandInterface`
* Change parameters order to from `$table, $columns, $rows` to `$table, $rows, $columns`
* Add default value `[]` for `$columns` parameter
From `batchInsert(string $table, array $columns, iterable $rows)`
to `insertBatch(string $table, iterable $rows, array $columns = [])`
* yiisoft/db-sqlite#301
* yiisoft/db-mysql#334
* yiisoft/db-pgsql#344
* yiisoft/db-oracle#268
* yiisoft/db-mssql#302
| Fixed issues  | #772
> Rename `batchInsert()` to `insertBatch()` and change paremeters order

- CHANGELOG.md
- UPGRADE.md
- src/QueryBuilder/AbstractDMLQueryBuilder.php
> Remove `AbstractDMLQueryBuilder::getTypecastValue()` method

- CHANGELOG.md
- UPGRADE.md
- src/QueryBuilder/AbstractDMLQueryBuilder.php
Remove `$table` parameter from `normalizeColumnNames()` and `getNormalizeColumnNames()` methods of `AbstractDMLQueryBuilder` class
> Remove `$table` parameter from `normalizeColumnNames()`

- CHANGELOG.md
- UPGRADE.md
- src/Schema/SchemaInterface.php
> Remove `SchemaInterface::TYPE_JSONB` constant

- CHANGELOG.md
- UPGRADE.md
- src/Schema/AbstractTableSchema.php
- src/Schema/TableSchemaInterface.php
- tests/AbstractTableSchemaTest.php
> Remove `TableSchemaInterface::compositeForeignKey()` method

- CHANGELOG.md
- UPGRADE.md
- src/Schema/Quoter.php
- src/Schema/QuoterInterface.php
> Remove parameter `$withColumn` from `Quoter::getTableNameParts()`

- CHANGELOG.md
- UPGRADE.md
- src/Command/AbstractCommand.php
- src/Driver/Pdo/AbstractPdoCommand.php
- tests/Common/CommonCommandTest.php
- tests/Common/CommonPdoCommandTest.php
- tests/Support/Stub/Command.php
Remove `$rawSql` parameter from
* `AbstractCommand::internalExecute()` method
* `AbstractPdoCommand::internalExecute()` method
> Remove `$rawSql` parameter from `AbstractCommand::internalExecute()` method

- CHANGELOG.md
- UPGRADE.md
- src/Query/Query.php
- src/Query/QueryPartsInterface.php
- tests/Provider/QueryBuilderProvider.php
> Allow `ExpressionInterface` for `$alias` parameter of `QueryPartsInterface::withQuery()`

- CHANGELOG.md
- UPGRADE.md
- src/Schema/AbstractSchema.php
- tests/Db/Schema/SchemaTest.php
> Remove `AbstractSchema::normalizeRowKeyCase()` method

- CHANGELOG.md
- UPGRADE.md
- src/Schema/AbstractSchema.php
- src/Schema/SchemaInterface.php
> Remove `SchemaInterface::isReadQuery()` method

- CHANGELOG.md
- UPGRADE.md
- src/Schema/AbstractSchema.php
- src/Schema/SchemaInterface.php
> Remove `SchemaInterface::getRawTableName()` method

- rector.php
- src/Debug/CommandInterfaceProxy.php
- src/QueryBuilder/AbstractDMLQueryBuilder.php
- src/Schema/Quoter.php
- tests/Common/CommonCommandTest.php
> Apply rector on PHP 8.1 update

- src/Syntax/ColumnDefinitionParser.php
> Improve psalm annotations in `ColumnDefinitionParser`

- CHANGELOG.md
- src/Schema/Column/AbstractColumnFactory.php
- tests/Common/CommonSchemaTest.php
- tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/db-mysql/pull/361
- https://github.com/yiisoft/db-sqlite/pull/325
- https://github.com/yiisoft/db-pgsql/pull/368
- https://github.com/yiisoft/db-mssql/pull/327
- https://github.com/yiisoft/db-oracle/pull/288
| Fixed issues  | #854, #695
> Refactor `AbstractColumnFactory`

- CHANGELOG.md
- src/Schema/Column/AbstractColumnFactory.php
- src/Schema/Column/ColumnFactoryInterface.php
- tests/AbstractColumnFactoryTest.php
- tests/Provider/ColumnFactoryProvider.php
- https://github.com/yiisoft/db-pgsql/pull/370
- https://github.com/yiisoft/db-mysql/pull/363
- https://github.com/yiisoft/db-sqlite/pull/326
- https://github.com/yiisoft/db-mssql/pull/328
- https://github.com/yiisoft/db-oracle/pull/289
- https://github.com/yiisoft/active-record/pull/390
> Refactor `normalizeDefaultValue()`

- CHANGELOG.md
- UPGRADE.md
- src/Connection/ConnectionInterface.php
- src/Connection/ServerInfoInterface.php
- src/Debug/ConnectionInterfaceProxy.php
- src/Driver/Pdo/AbstractPdoConnection.php
- src/Driver/Pdo/PdoServerInfo.php
- src/QueryBuilder/AbstractQueryBuilder.php
- src/QueryBuilder/QueryBuilderInterface.php
- tests/AbstractPdoConnectionTest.php
- tests/Common/CommonColumnSchemaBuilderTest.php
- tests/Common/CommonPdoConnectionTest.php
- tests/Db/Driver/PDO/PdoServerInfoTest.php
- tests/Db/QueryBuilder/QueryBuilderTest.php
- tests/Support/Stub/Connection.php
- tests/Support/Stub/QueryBuilder.php
- https://github.com/yiisoft/db-sqlite/pull/330
- https://github.com/yiisoft/db-pgsql/pull/375
- https://github.com/yiisoft/db-mysql/pull/368
- https://github.com/yiisoft/db-mssql/pull/333
- https://github.com/yiisoft/db-oracle/pull/294
> Add `ServerInfoInterface` and its implementation

- src/Schema/Column/ColumnBuilder.php
- https://github.com/yiisoft/db-mysql/pull/370
| Fixed issues  | yiisoft/db-mysql#2
> Update doc of `ColumnBuilder::text()`

- CHANGELOG.md
- UPGRADE.md
- src/QueryBuilder/AbstractDDLQueryBuilder.php
- src/Schema/Column/AbstractColumn.php
- src/Schema/Column/ColumnInterface.php
- tests/Db/Command/CommandTest.php
- tests/Db/Schema/Column/ColumnTest.php
- tests/Support/Stub/ColumnDefinitionBuilder.php
> Replace `name()` with immutable `withName()` in `ColumnInterface`

- src/Command/CommandInterface.php
- src/Query/QueryInterface.php
> Add PHPDoc about `boolean` values in `scalar()` and `queryScalar()`

- CHANGELOG.md
- UPGRADE.md
- docs/guide/en/queries/transactions.md
- docs/guide/pt-BR/queries/transactions.md
- src/Command/CommandInterface.php
- src/Command/Param.php
- src/Command/ParamInterface.php
- src/Constant/DataType.php
- src/QueryBuilder/AbstractQueryBuilder.php
- src/Schema/AbstractSchema.php
- src/Schema/SchemaInterface.php
- tests/AbstractQueryBuilderTest.php
- tests/AbstractSchemaTest.php
- tests/Common/CommonCommandTest.php
- tests/Provider/CommandPDOProvider.php
- tests/Provider/CommandProvider.php
- tests/Provider/QueryBuilderProvider.php
> Move `DataType` class to `Yiisoft\Db\Constant` namespace

- CHANGELOG.md
- UPGRADE.md
- src/Helper/DbArrayHelper.php
- src/Query/BatchQueryResultInterface.php
- src/Query/Query.php
- src/Query/QueryInterface.php
- tests/Db/Helper/DbArrayHelperTest.php
- tests/Provider/DbArrayHelperProvider.php
- https://github.com/yiisoft/db-sqlite/pull/335
- https://github.com/yiisoft/db-mysql/pull/373
- https://github.com/yiisoft/db-pgsql/pull/382
- https://github.com/yiisoft/db-mssql/pull/338
- https://github.com/yiisoft/db-oracle/pull/300
| Fixed issues  | #817
> Refactor `DbArrayHelper`

- CHANGELOG.md
- UPGRADE.md
- src/Command/CommandInterface.php
- src/Constant/IndexType.php
- src/QueryBuilder/DDLQueryBuilderInterface.php
- src/Schema/SchemaInterface.php
- tests/Common/CommonCommandTest.php
- tests/Common/CommonSchemaTest.php
- tests/Provider/CommandProvider.php
- tests/Provider/QueryBuilderProvider.php
- tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/db-mysql/pull/374
- https://github.com/yiisoft/db-pgsql/pull/384
- https://github.com/yiisoft/db-mssql/pull/339
- https://github.com/yiisoft/db-oracle/pull/301
- https://github.com/yiisoft/db-migration/pull/285
> Move index type constants to `IndexType` class

- CHANGELOG.md
- UPGRADE.md
- docs/guide/en/command/ddl.md
- docs/guide/pt-BR/command/ddl.md
- src/Command/CommandInterface.php
- src/Constant/ReferentialAction.php
- src/Constraint/ForeignKeyConstraint.php
- src/QueryBuilder/AbstractColumnDefinitionBuilder.php
- src/QueryBuilder/DDLQueryBuilderInterface.php
- tests/Db/Command/CommandTest.php
- tests/Provider/CommandProvider.php
- tests/Provider/QueryBuilderProvider.php
- tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/db-mssql/pull/340
- https://github.com/yiisoft/db-oracle/pull/302
| Fixed issues  | #739, #659
> Add `ReferentialAction` class

- CHANGELOG.md
- composer.json
- https://github.com/yiisoft/db-sqlite/pull/343
- https://github.com/yiisoft/db-mysql/pull/382
- https://github.com/yiisoft/db-pgsql/pull/390
- https://github.com/yiisoft/active-record/pull/406
> Remove `yiisoft/json` from `require-dev` section of `composer.json`

- CHANGELOG.md
- UPGRADE.md
- src/Command/AbstractCommand.php
- src/Connection/ConnectionInterface.php
- src/Debug/ConnectionInterfaceProxy.php
- src/QueryBuilder/AbstractColumnDefinitionBuilder.php
- src/QueryBuilder/AbstractQueryBuilder.php
- src/QueryBuilder/Condition/Builder/AbstractOverlapsConditionBuilder.php
- src/QueryBuilder/Condition/Builder/BetweenColumnsConditionBuilder.php
- src/QueryBuilder/Condition/Builder/BetweenConditionBuilder.php
- src/QueryBuilder/Condition/Builder/HashConditionBuilder.php
- src/QueryBuilder/Condition/Builder/InConditionBuilder.php
- src/QueryBuilder/Condition/Builder/LikeConditionBuilder.php
- src/QueryBuilder/Condition/Builder/SimpleConditionBuilder.php
- src/QueryBuilder/QueryBuilderInterface.php
- src/Schema/SchemaInterface.php
- tests/AbstractColumnFactoryTest.php
- tests/AbstractQueryBuilderTest.php
- tests/Common/CommonPdoConnectionTest.php
- tests/Common/CommonQueryBuilderTest.php
- tests/Db/Command/CommandTest.php
- tests/Db/Connection/ConnectionTest.php
- tests/Db/QueryBuilder/QueryBuilderTest.php
- tests/Support/Stub/ColumnDefinitionBuilder.php
- tests/Support/Stub/Connection.php
- tests/Support/Stub/QueryBuilder.php
- tests/Support/Stub/Schema.php
- move `getColumnFactory()` from `SchemaInterface` to `ConnectionInterface`
- rename `QueryBuilderInterface::quoter()` to `QueryBuilderInterface::getQuoter()`
- remove `QueryBuilderInterface::getSchema()`
- add `QueryBuilderInterface::getColumnFactory()`
- change parameters in `AbstractQueryBuilder::__construct()`
- other minor refactoring
- https://github.com/yiisoft/db-sqlite/pull/345
- https://github.com/yiisoft/db-mysql/pull/384
- https://github.com/yiisoft/db-pgsql/pull/393
- https://github.com/yiisoft/db-mssql/pull/350
- https://github.com/yiisoft/db-oracle/pull/313
> Refactofing

- CHANGELOG.md
- src/Schema/Column/AbstractColumnFactory.php
- tests/Common/CommonSchemaTest.php
- tests/Support/Assert.php
- https://github.com/yiisoft/db-sqlite/pull/349
- https://github.com/yiisoft/db-mysql/pull/388
- https://github.com/yiisoft/db-pgsql/pull/399
- https://github.com/yiisoft/db-mssql/pull/354
- https://github.com/yiisoft/db-oracle/pull/317
- https://github.com/yiisoft/db-migration/pull/291
> Refactor test of columns

- CHANGELOG.md
- UPGRADE.md
- docker/Dockerfile
- src/Helper/DbArrayHelper.php
- src/Query/Query.php
- tests/Db/Helper/DbArrayHelperTest.php
- tests/Provider/DbArrayHelperProvider.php
- https://github.com/yiisoft/db-sqlite/pull/350
- https://github.com/yiisoft/db-mysql/pull/389
- https://github.com/yiisoft/db-pgsql/pull/403
- https://github.com/yiisoft/db-mssql/pull/355
- https://github.com/yiisoft/db-oracle/pull/318
> Add `DbArrayHelper::arrange()` method

- CHANGELOG.md
- UPGRADE.md
- src/Driver/Pdo/AbstractPdoCommand.php
- src/Driver/Pdo/AbstractPdoConnection.php
- src/Driver/Pdo/AbstractPdoTransaction.php
- src/Driver/Pdo/PdoConnectionInterface.php
- src/Driver/Pdo/PdoServerInfo.php
- tests/AbstractConnectionTest.php
- tests/AbstractPdoConnectionTest.php
- tests/Common/CommonCommandTest.php
- tests/Common/CommonPdoCommandTest.php
- tests/Common/CommonPdoConnectionTest.php
- tests/Common/CommonSchemaTest.php
- tests/Support/DbHelper.php
Fix #908 
+ Rename `getActivePDO()` to `getActivePdo()` and `getPDO()` to `getPdo()`.
> Remove nullable from `PdoConnectionInterface::getActivePdo()` result + Minor refactor

- CHANGELOG.md
- UPGRADE.md
- src/Query/Query.php
- src/Query/QueryPartsInterface.php
- tests/AbstractQueryBuilderTest.php
Added `->where(force: true)` to protect against accidental overwriting `where` condition
| Fixed issues  | 
```php
$query = (new Query($db))
->where(['like', 'name', 'foo%'])
->where(['not like', 'name', 'foo%']); // => throw new LogicException()
```
This solves the problem of accidentally overriding the `where` condition.
If you really want to redefine `where`, then you should use the `setWhere()` or `andWhere()` or `orWhere()` method.
```php
$query = (new Query($db))
->where(['like', 'name', 'foo%'])
->setWhere(['not like', 'name', 'foo%']);
$this->assertEquals(['not like', 'name', 'foo%'], $query->getWhere());
```
> Added `->setWhere()` as force method `->where()`

- CHANGELOG.md
- src/Query/Query.php
- tests/AbstractQueryTest.php
> Make `Query::andHaving()` like `Query::andWhere()`

- CHANGELOG.md
- UPGRADE.md
- src/Command/AbstractCommand.php
- src/Expression/ExpressionBuilder.php
- src/QueryBuilder/AbstractDDLQueryBuilder.php
- src/QueryBuilder/AbstractDQLQueryBuilder.php
- src/QueryBuilder/AbstractQueryBuilder.php
- src/QueryBuilder/DQLQueryBuilderInterface.php
- src/QueryBuilder/QueryBuilderInterface.php
- tests/AbstractQueryBuilderTest.php
- tests/Provider/QueryBuilderProvider.php
- tests/Support/Stub/DQLQueryBuilder.php
- tests/Support/Stub/QueryBuilder.php
- https://github.com/yiisoft/db-sqlite/pull/352
- https://github.com/yiisoft/db-mysql/pull/391
- https://github.com/yiisoft/db-pgsql/pull/405
- https://github.com/yiisoft/db-mssql/pull/357
- https://github.com/yiisoft/db-oracle/pull/321
| Fixed issues  | #903
> Move `replacePlaceholders()` to `QueryBuilderInterface`

- CHANGELOG.md
- src/Connection/ConnectionInterface.php
- src/Debug/ConnectionInterfaceProxy.php
- src/Driver/Pdo/AbstractPdoConnection.php
- tests/Common/CommonCommandTest.php
- tests/Common/CommonPdoConnectionTest.php
- tests/Db/Driver/PDO/PdoConnectionTest.php
- tests/Support/Stub/Schema.php
Fix #879 
Related PRs:
- https://github.com/yiisoft/db-mysql/pull/392
- https://github.com/yiisoft/db-oracle/pull/322
- https://github.com/yiisoft/db-pgsql/pull/406
- https://github.com/yiisoft/db-sqlite/pull/353
> Rename `getLastInsertID()` method in `ConnectionInterface` to `getLastInsertId()`

- CHANGELOG.md
- UPGRADE.md
- docs/guide/en/query-builder/building-queries.md
- docs/guide/en/query/for.md
- src/Query/Query.php
- src/Query/QueryInterface.php
- src/Query/QueryPartsInterface.php
- src/QueryBuilder/AbstractDQLQueryBuilder.php
- src/QueryBuilder/AbstractQueryBuilder.php
- src/QueryBuilder/DQLQueryBuilderInterface.php
- tests/AbstractQueryBuilderTest.php
- tests/Db/Query/QueryTest.php
- tests/Db/QueryBuilder/QueryBuilderTest.php
Fix #813 
Related PRs:
- https://github.com/yiisoft/db-sqlite/pull/354
> Add `FOR` clause for query

- CHANGELOG.md
- src/QueryBuilder/AbstractDQLQueryBuilder.php
- tests/AbstractQueryBuilderTest.php
- tests/Provider/QueryBuilderProvider.php
- https://github.com/yiisoft/db-mssql/pull/363
- https://github.com/yiisoft/db-oracle/pull/326
| Fixed issues  | https://github.com/yiisoft/yii2/issues/20385
> Fix memory leaking in `Command::exists()` method

- CHANGELOG.md
- src/Command/AbstractCommand.php
- src/Driver/Pdo/AbstractPdoCommand.php
- tests/Common/CommonCommandTest.php
Fix #782 
Related PRs:
- https://github.com/yiisoft/db-oracle/pull/337
> Remove `requireTransaction()` and `$isolationLevel` from `AbstractCommand`

- CHANGELOG.md
- src/Schema/Quoter.php
- src/Schema/QuoterInterface.php
- tests/AbstractQuoterTest.php
- tests/Db/Schema/QuoterTest.php
- tests/Provider/QuoterProvider.php
- https://github.com/yiisoft/db-sqlite/pull/376
- https://github.com/yiisoft/db-mysql/pull/413
- https://github.com/yiisoft/db-pgsql/pull/430
- https://github.com/yiisoft/db-mssql/pull/382
- https://github.com/yiisoft/db-oracle/pull/347
> Improve `Quoter::getTableNameParts()` method

- CHANGELOG.md
- UPGRADE.md
- docs/guide/en/query/where.md
- src/QueryBuilder/Condition/Builder/LikeBuilder.php
- src/QueryBuilder/Condition/Like.php
- tests/Db/QueryBuilder/Condition/LikeTest.php
- tests/Provider/QueryBuilderProvider.php
Relative PRs:
- https://github.com/yiisoft/db-oracle/pull/350
> Replace "escaping replacements" methods with "escape" constructor parameter in `Like`

- CHANGELOG.md
- src/QueryBuilder/AbstractDMLQueryBuilder.php
> Refactor `AbstractDMLQueryBuilder::getTableUniqueColumnNames()` method

- CHANGELOG.md
- UPGRADE.md
- src/Connection/AbstractConnection.php
- src/Connection/ConnectionInterface.php
- src/Debug/ConnectionInterfaceProxy.php
- tests/AbstractColumnBuilderTest.php
- tests/AbstractConnectionTest.php
- tests/Common/CommonColumnTest.php
- https://github.com/yiisoft/db-sqlite/pull/385
- https://github.com/yiisoft/db-mysql/pull/421
- https://github.com/yiisoft/db-pgsql/pull/440
- https://github.com/yiisoft/db-mssql/pull/391
- https://github.com/yiisoft/db-oracle/pull/358
> Add `ConnectionInterface::getColumnBuilderClass()`

- CHANGELOG.md
- psalm.xml
- src/Expression/Function/ArrayMerge.php
- src/Expression/Function/Builder/GreatestBuilder.php
- src/Expression/Function/Builder/LeastBuilder.php
- src/Expression/Function/Builder/LengthBuilder.php
- src/Expression/Function/Builder/LongestBuilder.php
- src/Expression/Function/Builder/MultiOperandFunctionBuilder.php
- src/Expression/Function/Builder/ShortestBuilder.php
- src/Expression/Function/Greatest.php
- src/Expression/Function/Least.php
- src/Expression/Function/Length.php
- src/Expression/Function/Longest.php
- src/Expression/Function/MultiOperandFunction.php
- src/Expression/Function/Shortest.php
- src/QueryBuilder/AbstractDQLQueryBuilder.php
- src/Schema/Column/AbstractArrayColumn.php
- src/Schema/Column/AbstractStructuredColumn.php
- src/Schema/Column/ArrayColumn.php
- src/Schema/Column/ArrayLazyColumn.php
- src/Schema/Column/DateTimeColumn.php
- src/Schema/Column/StructuredColumn.php
- src/Schema/Column/StructuredLazyColumn.php
- tests/AbstractQueryBuilderTest.php
- tests/Common/CommonQueryBuilderTest.php
- tests/Db/Expression/Function/ArrayMergeTest.php
- tests/Db/Expression/Function/LengthTest.php
- tests/Db/Expression/Function/MultiOperandFunctionTest.php
- tests/Provider/QueryBuilderProvider.php
- https://github.com/yiisoft/db-sqlite/pull/384
- https://github.com/yiisoft/db-mysql/pull/420
- https://github.com/yiisoft/db-pgsql/pull/439
- https://github.com/yiisoft/db-mssql/pull/390
- https://github.com/yiisoft/db-oracle/pull/357
> Add functions as expressions

- CHANGELOG.md
- src/QueryBuilder/AbstractDMLQueryBuilder.php
- tests/AbstractQueryBuilderTest.php
- tests/Common/CommonCommandTest.php
- tests/Common/CommonQueryBuilderTest.php
- tests/Db/QueryBuilder/QueryBuilderTest.php
- tests/Provider/QueryBuilderProvider.php
- https://github.com/yiisoft/db-sqlite/pull/387
- https://github.com/yiisoft/db-mysql/pull/423
- https://github.com/yiisoft/db-pgsql/pull/442
- https://github.com/yiisoft/db-mssql/pull/393
- https://github.com/yiisoft/db-oracle/pull/360
> Refactor `AbstractDMLQueryBuilder::upsert()`

- CHANGELOG.md
- src/QueryBuilder/AbstractDMLQueryBuilder.php
- tests/Common/CommonCommandTest.php
- tests/Common/CommonQueryBuilderTest.php
- tests/Provider/QueryBuilderProvider.php
Related PRs:
- https://github.com/yiisoft/db-sqlite/pull/388
- https://github.com/yiisoft/db-pgsql/pull/443
- https://github.com/yiisoft/db-oracle/pull/361
- https://github.com/yiisoft/db-mysql/pull/425
- https://github.com/yiisoft/db-mssql/pull/394
> Reduce binding parameters on insert

- CHANGELOG.md
- src/Expression/Function/ArrayMerge.php
- tests/Db/Expression/Function/ArrayMergeTest.php
- https://github.com/yiisoft/db-sqlite/pull/390
- https://github.com/yiisoft/db-mysql/pull/427
- https://github.com/yiisoft/db-pgsql/pull/446
- https://github.com/yiisoft/db-mssql/pull/396
- https://github.com/yiisoft/db-oracle/pull/363
> Add `ordered` option to `ArrayMerge`

- CHANGELOG.md
- src/QueryBuilder/Condition/AbstractLike.php
- src/QueryBuilder/Condition/Builder/LikeBuilder.php
- tests/Db/QueryBuilder/Condition/Builder/LikeBuilderTest.php
Related PRs:
- https://github.com/yiisoft/db-oracle/pull/368
> `Stringable` value support in `Like` and `NotLike` conditions
