src/Migration.php

| Is bugfix?    | yes
| Breaks BC?    | yes

Refactored for Yii 3.0 support.

---

src/Transaction.php
tests/unit/ConnectionTest.php

| Is bugfix?    | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii2/issues/16424

Savepoint unsupported detection in transaction begin

---

.travis.yml
composer.json
composer.lock

| Is bugfix?    | no
| Breaks BC?    | no
| Tests pass?   | will see
| Fixed issues  | non-working tests

Fix travis

---

src/Connection.php

Added dns example
http://php.net/manual/en/pdo.construct.php
http://php.net/manual/en/ref.pdo-mysql.connection.php
https://github.com/yiisoft/db/pull/13

Added dns example

---

src/Command.php
src/Connection.php
src/Query.php
src/Schema.php

| Is bugfix?    | yes
| Breaks BC?    | no

Fix namespace y update comments

---

src/Connection.php

Restore $charset in yii\db\Connection

---

composer.json
config/common.php

\yii\di\Reference -> Yiisoft\Factory\Definitions\Reference
| Is bugfix?    | yes
| Breaks BC?    | no
| Tests pass?   | no

Common config

---

src/Exception.php
src/InvalidConfigException.php
src/NotSupportedException.php

| Tests pass?   | ❌
| Fixed issues  | Added exception classes to make component independent

Added Exceptions classes.

---

src/Querys/Query.php

| Fixed issues  | https://github.com/yiisoft/yii2/pull/17881

queryScalar() fix #17881.

---

src/Drivers/Connection.php

The properties will be changed to private once you add the setters and getters `Connetion::class` to the entire package and tests.

Clean up Connection class.

---

src/Commands/Command.php
src/Drivers/Connection.php
src/Factory/DatabaseFactory.php
src/Schemas/Schema.php
src/Transactions/Transaction.php
tests/ConnectionTest.php

Improve connection class.

---

src/Drivers/Connection.php
tests/QueryBuilderTest.php

Fix tests db-sqlite.

---

src/Commands/Command.php
src/Data/DataReader.php
src/Querys/Query.php
tests/CommandTest.php

Improve command class.

---

src/Expressions/ArrayExpression.php
src/Expressions/Expression.php
src/Expressions/ExpressionBuilder.php
src/Expressions/ExpressionBuilderInterface.php
src/Expressions/ExpressionBuilderTrait.php
src/Expressions/ExpressionInterface.php
src/Expressions/JsonExpression.php
src/Querys/QueryBuilder.php

Improve expressions classes.

---

src/Pdo/PdoValueBuilder.php

Fix ExpressionBuilderInterface typehints.

---

src/Helper/Dsn.php
src/Pdo/PdoValue.php
src/Querys/Conditions/BetweenColumnsCondition.php
src/Querys/Conditions/BetweenColumnsConditionBuilder.php
src/Querys/Conditions/BetweenCondition.php
src/Querys/Conditions/ConjunctionCondition.php
src/Querys/Conditions/ConjunctionConditionBuilder.php
src/Querys/Conditions/ExistsCondition.php
src/Querys/Conditions/HashCondition.php
src/Querys/Conditions/HashConditionBuilder.php
src/Querys/Conditions/InCondition.php
src/Querys/Conditions/LikeCondition.php
src/Querys/Conditions/LikeConditionBuilder.php
src/Querys/Conditions/NotCondition.php
src/Querys/Conditions/NotConditionBuilder.php
src/Querys/Conditions/SimpleCondition.php

Improve dsn, pdovalue and conditions classes.

---

src/Querys/Query.php
src/Querys/QueryBuilder.php
tests/QueryBuilderTest.php
tests/QueryTest.php

Add PR 17344, 17403, issue #100.

---

src/Query/QueryBuilder.php

Add setter QueryBuilder.

---

src/Schema/ColumnSchema.php
src/Schema/Schema.php
tests/CommandTest.php
tests/SchemaTest.php

Improve columschema class.

---

.github/workflows/build.yml

GitHub Actions Breaking Change Mysql.

---

src/Transaction/Transaction.php
src/View/ViewFinderTrait.php

Improve transaction y viewfindertrait class.

---

src/Schema/Schema.php

Fix correction in tableschema class.

---

src/Connection/Connection.php
src/Constraint/IndexConstraint.php
src/Data/DataReader.php
src/Query/QueryBuilder.php
src/Schema/ColumnSchema.php
src/Schema/ColumnSchemaBuilder.php
src/Schema/Schema.php
src/Schema/TableSchema.php
src/Transaction/Transaction.php
tests/CommandTest.php
tests/ConnectionTest.php
tests/SchemaTest.php

Rename getMethod() that return bool as isMethod().

---

src/Schema/Schema.php

Add typehints.

---

src/Query/Conditions/InConditionBuilder.php

Add typehint.

---

src/Schema/Schema.php
tests/SchemaTest.php

Fix tests db-pgsql.

---

src/Constraint/CheckConstraint.php
src/Constraint/Constraint.php
src/Constraint/DefaultValueConstraint.php
src/Constraint/ForeignKeyConstraint.php
src/Constraint/IndexConstraint.php
tests/SchemaTest.php

Rework code setters constraint classes.

---

tests/SchemaTest.php

Rework code setters constraint classes in tests.

---

.github/workflows/build.yml

Use services for MySQL and PostgreSQL tests - github actions.

---

tests/QueryBuilderTest.php

| Fixed issues  | https://github.com/yiisoft/db-mysql/issues/1

Add support port fractional seconds.

---

tests/QueryBuilderTest.php

Fix phpdocs.

---

src/Exception/InvalidArgumentException.php
src/Exception/InvalidConfigException.php
src/Exception/InvalidParamException.php

Add InvalidParamException class.

---

src/Query/Query.php
src/Query/QueryTrait.php

Remove magic method Configure().

---

tests/QueryBuilderTest.php

| Fixed issues  | https://github.com/yiisoft/yii2/issues/17960

Fix unsigned primary key type mapping for SQLite.

---

src/Event/AfterSaveEvent.php
src/Query/Conditions/SimpleConditionBuilder.php
src/Query/QueryInterface.php

Add declare

---

config/tests.php
src/Command/Command.php
src/Connection/Connection.php

Fix test php 8.0.

---

src/Schema/Schema.php

Fix typehint $tableQuoteCharacter, $columnQuoteCharacter in Schema::class.

---

src/Schema/Schema.php

Fix typehint Schema::convertException().

---

src/Connection/Connection.php

Add support db-mssql.

---

src/Connection/Connection.php
src/Query/BatchQueryResult.php

Fix typehint and simplify getDriverName().

---

src/Query/QueryBuilder.php
src/Schema/ColumnSchema.php
src/Schema/ColumnSchemaBuilder.php

Fix typehint NumericHelper::normalize().

---

src/Command/Command.php
src/Connection/Connection.php
src/Connection/ConnectionPool.php
src/Data/DataReaderProvider.php
src/Query/BatchQueryResult.php
src/Query/Query.php
src/Query/QueryBuilder.php
src/Schema/Schema.php
src/Schema/SchemaBuilderTrait.php

Use ConnectionInterface::class.

---

composer.json
phpunit.xml.dist
src/Connection/ConnectionPool.php

Add tests active-record, fix namespace.

---

src/Connection/ConnectionInterface.php

I am adding the methods that PSALM indicates to me in the implementations, so we do not add unused methods.

Add methods connectioninterface

---

src/Query/Query.php
src/TestUtility/TestQueryTrait.php

| Fixed issues  | https://github.com/yiisoft/yii2/issues/18066

db/Query::withQuery() not working.

---

src/Query/Query.php

| Fixed issues  | https://github.com/yiisoft/arrays/issues/48

Fix ArrayHelper changes.

---

src/Query/QueryTrait.php

Add method isEmulateExecution() in QueryTrait::class.

---

src/Query/QueryInterface.php

Fix typehints QueryInterface::class.

---

src/Constraint/CheckConstraint.php
src/Constraint/Constraint.php
src/Constraint/ConstraintFinderInterface.php
src/Constraint/DefaultValueConstraint.php
src/Constraint/ForeignKeyConstraint.php
src/Constraint/IndexConstraint.php
src/Query/QueryBuilder.php
src/Schema/Schema.php

Change the ConnectionInterface::class visibility protected to private, remove null.

---

src/Command/Command.php
src/Connection/Connection.php
src/Connection/ConnectionInterface.php
src/Data/DataProvider.php
src/Exception/Exception.php
src/Query/Query.php
src/Query/QueryBuilder.php
src/Schema/Schema.php
src/TestUtility/IsOneOfAssert.php

| Issue | https://github.com/yiisoft/db/issues/152

Fix psalm issues.

---

src/Command/Command.php
src/Connection/Connection.php
src/Schema/Schema.php

Fix key cache string.

---

.github/workflows/build.yml
.github/workflows/db-mssql.yml
.github/workflows/db-mysql.yml
.github/workflows/db-pgsql.yml
.github/workflows/static.yml

Update github actions.

---

src/Connection/Connection.php
src/Connection/Dsn.php

Related PRs:
- https://github.com/yiisoft/active-record/pull/121
- https://github.com/yiisoft/db-pgsql/pull/49
- https://github.com/yiisoft/db-mysql/pull/59
- https://github.com/yiisoft/db-sqlite/pull/43

Move Dsn to Connection namespace

---

README.md

Update static analysis section in README

---

src/TestUtility/TestCommandTrait.php
src/TestUtility/TestConnectionTrait.php
src/TestUtility/TestQueryBuilderTrait.php
src/TestUtility/TestQueryTrait.php

| Issue | https://github.com/yiisoft/db-oracle/pull/15

Fixed tests oracle.

---

.github/workflows/build.yml
.scrutinizer.yml
composer.json
phpunit.xml.dist
src/TestUtility/TestConnectionTrait.php

Fix test enable query log

---

src/Schema/Schema.php

Fixed tests.

---

src/Command/Command.php
src/Connection/Connection.php

Adjust to yiisoft/profiler changes

---

src/Cache/SchemaCache.php
src/Connection/Connection.php
src/Schema/Schema.php

Replace SchemaCache::get to SchemaCache::getOrSet for correct work with PSR caches

---

src/Schema/Schema.php

Fix tag dependency.

---

src/Schema/Schema.php

 Fix tag dependency.

---

src/Connection/LazyConnectionDependencies.php

| Fixed issues  | https://github.com/yiisoft/factory/pull/78

Adjust namespaces

---

src/Connection/LazyConnectionDependencies.php
src/Data/SqlDataProvider.php

Update factory changes

---

src/Factory/DatabaseFactory.php
src/Query/QueryBuilder.php

Fix: from yiisoft/factory - removed FactoryInterface, and class Factory is now - final

Change DatabaseFactory class

---

composer.json
src/Connection/LazyConnectionDependencies.php

Adopt to `yiisoft/definitions`

---

src/Connection/LazyConnectionDependencies.php

Remove DependencyResolver

---

composer.json
src/Schema/TableSchema.php
src/TestUtility/TestSchemaTrait.php

Fix return type TableSchema::getcolumn().

---

src/Data/DataReader.php
src/Expression/ArrayExpression.php
src/Expression/JsonExpression.php
src/Query/BatchQueryResult.php
src/TestUtility/TraversableObject.php

Remove `PHP 8.1` depreciation messages.

---

src/Cache/QueryCache.php
src/Cache/SchemaCache.php

Allow null duration `SchemaCache`, `QueryCache`.

---

src/Schema/Schema.php

Remove ucfirst

---

src/Query/QueryBuilder.php
src/Schema/ColumnSchema.php
src/Schema/Quoter.php
src/Schema/QuoterInterface.php
src/Schema/TableSchema.php

| Fixed issues  | https://github.com/yiisoft/db-mssql/pull/68

Set psalm error level = 1 `yiisoft/db-mssql`.

---

src/Exception/ConvertException.php
src/Schema/Schema.php
src/Schema/SchemaInterface.php

Fix method `convertException()`

---

src/Command/Command.php
src/Command/CommandInterface.php
src/Command/CommandPdoTrait.php
src/Query/DMLQueryBuilder.php
src/Query/QueryBuilder.php
src/Query/QueryBuilderInterface.php
src/TestSupport/TestCommandTrait.php

Pdo 2. Adding insertEx and partial removing usages of pdoStatement

---

src/Command/CommandPdoTrait.php

Pdo 2. Fix psalm

---

src/Query/Query.php

Remove static method.

---

src/Command/Command.php
src/Command/CommandInterface.php
src/TestSupport/TestCommandTrait.php

Third step of remove PDO. Using only fetchAll

---

src/Query/Query.php
src/Query/QueryInterface.php

| Fixed issues  | https://github.com/yiisoft/active-record/pull/173

Fix psalm-1 `Query::class`, `QueryInterface::class`.

---

src/Constraint/ConstraintSchemaInterface.php
src/Query/BatchQueryResult.php
src/Query/DDLQueryBuilder.php
src/Query/DMLQueryBuilder.php
src/Query/QueryBuilder.php
src/Query/QueryBuilderInterface.php
src/Query/QueryExpressionBuilder.php
src/Schema/ColumnSchema.php
src/Schema/ColumnSchemaBuilder.php
src/Schema/Quoter.php
src/Schema/QuoterInterface.php
src/Schema/Schema.php
src/Schema/SchemaInterface.php
src/Schema/TableSchema.php
src/Transaction/Transaction.php

Set error level to `1` psalm - part-2.

---

src/Command/Command.php

Fix for static analysis

---

src/Query/Conditions/BetweenColumnsCondition.php
src/Query/Conditions/BetweenCondition.php
src/Query/Conditions/Builder/ConjunctionConditionBuilder.php
src/Query/Conditions/Builder/HashConditionBuilder.php
src/Query/Conditions/Builder/InConditionBuilder.php
src/Query/Conditions/Builder/LikeConditionBuilder.php
src/Query/Conditions/ConjunctionCondition.php
src/Query/Conditions/ExistsCondition.php
src/Query/Conditions/HashCondition.php
src/Query/Conditions/InCondition.php
src/Query/Conditions/Interface/InConditionInterface.php
src/Query/Conditions/Interface/NotConditionInterface.php
src/Query/Conditions/LikeCondition.php
src/Query/Conditions/NotCondition.php
src/Query/Conditions/SimpleCondition.php
src/Query/Data/DataReader.php

Set error level to `1` psalm - part-3.

---

psalm.xml
src/Cache/QueryCache.php
src/Command/Command.php
src/Command/CommandInterface.php
src/Command/CommandPDO.php
src/Connection/Connection.php
src/Connection/Dsn.php
src/Exception/ConvertException.php
src/Expression/ArrayExpression.php
src/Expression/JsonExpression.php
src/Pdo/PdoValueBuilder.php
src/Query/QueryBuilder.php
src/Query/QueryHelper.php

Set error level to `1` psalm - part4.

---

src/Command/Command.php
src/Command/CommandInterface.php
src/Command/CommandPDO.php
src/Command/CommandPDOInterface.php
src/Query/BatchQueryResult.php
src/Query/Data/DataReader.php
src/Query/Data/DataReaderInterface.php
src/TestSupport/TestBatchQueryResultTrait.php
src/TestSupport/TestCommandTrait.php

Step 5 (remove PDO). Add CommandPDOInterface and cleanup of DataReader

---

src/Command/Command.php

Remove array_map from `getParams()`, and fix minor corrections.

---

src/Command/Command.php
src/Query/QueryBuilder.php
src/TestSupport/AnyCaseValue.php
src/TestSupport/IsOneOfAssert.php

Remove unnecesary `array map` function.

---

src/Command/Command.php
src/Command/CommandInterface.php
src/Query/Query.php
src/TestSupport/TestCommandTrait.php
src/TestSupport/TestQueryTrait.php

Fix for query* functions and tests

---

src/Command/CommandPDO.php
src/Connection/Connection.php
src/Connection/ConnectionInterface.php
src/Connection/ConnectionPDO.php
src/Connection/ConnectionPDOInterface.php
src/Connection/ConnectionPDOPoolInterface.php
src/TestSupport/TestCommandTrait.php
src/TestSupport/TestQueryBuilderTrait.php
src/TestSupport/TestSchemaTrait.php

Simplification of Connection - removing pool from Connection

---

src/Connection/ConnectionPDO.php

Common constructor for ConnectionPDO

---

src/Command/CommandPDO.php
src/Connection/ConnectionInterface.php
src/Connection/ConnectionPDO.php
src/Connection/ConnectionPDOInterface.php
src/TestSupport/TestConnectionTrait.php

Removing getDriver from ConnectionPDO classes

---

src/Connection/Connection.php
src/Connection/ConnectionInterface.php
src/Connection/ConnectionPDO.php
src/Schema/SchemaInterface.php
src/TestSupport/TestCommandTrait.php

Refactoring lastInsertId

---

src/Schema/SchemaInterface.php
src/TestSupport/TestConnectionTrait.php
src/Transaction/TransactionInterface.php
src/Transaction/TransactionPDO.php

Removing transactionIsolationLevel & operations with savepoint from Schema

---

src/TestSupport/TestConnectionTrait.php

Minifix for tests

---

src/Schema/ColumnSchema.php
src/Schema/Schema.php
src/TestSupport/TestSchemaTrait.php

Changed strings to constants. Added tests.

---

.github/workflows/active-record.yml
.github/workflows/db-mssql.yml
.github/workflows/db-mysql.yml
.github/workflows/db-oracle.yml
.github/workflows/db-pgsql.yml
.github/workflows/db-sqlite.yml
.github/workflows/static.yml

Update dependencies workflows.

---

src/Command/CommandInterface.php
src/Driver/PDO/CommandPDO.php
src/Driver/PDO/CommandPDOInterface.php
src/Driver/PDO/ConnectionPDO.php
src/Driver/PDO/ConnectionPDOInterface.php
src/Driver/PDO/ConnectionPDOPoolInterface.php
src/Driver/PDO/PDODriver.php
src/Driver/PDO/PDOValue.php
src/Driver/PDO/PDOValueBuilder.php
src/Driver/PDO/TransactionPDO.php
src/Query/Data/DataReader.php
src/Query/QueryBuilder.php
src/Schema/ColumnSchema.php

Move classes `PDO` to directory `src/Driver/PDO`.

---

src/Command/Command.php
src/Command/CommandInterface.php
src/Query/DDLQueryBuilder.php
src/Query/DDLQueryBuilderInterface.php
src/Query/DMLQueryBuilder.php
src/Query/DMLQueryBuilderInterface.php
src/Query/QueryBuilder.php
src/Schema/TableSchema.php
src/Schema/TableSchemaInterface.php
src/TestSupport/Provider/QueryBuilderProvider.php
src/TestSupport/TestCommandTrait.php

Refactoring createIndex and more cleanup of code

---

src/Driver/PDO/ConnectionPDO.php
src/Driver/PDO/PDODriver.php
src/Driver/PDO/PDODriverInterface.php
src/Exception/ConvertException.php
src/TestSupport/TestQueryBuilderTrait.php

Work with attributes on connection

---

src/Query/Conditions/Builder/InConditionBuilder.php
src/Query/DQLQueryBuilder.php
src/Query/DQLQueryBuilderInterface.php
src/Query/Query.php
src/Query/QueryInterface.php
src/Query/QueryPartsInterface.php
src/TestSupport/GetTablesAliasTestTrait.php
src/TestSupport/TestQueryTrait.php

Usage QueryInterface

---

src/Command/Command.php
src/Connection/Connection.php
src/Data/Sort.php
src/Data/SqlDataProvider.php
src/Query/BatchQueryResult.php
src/Query/Conditions/BetweenColumnsConditionBuilder.php
src/Query/Conditions/BetweenConditionBuilder.php
src/Query/Conditions/HashConditionBuilder.php
src/Query/Conditions/InConditionBuilder.php
src/Query/Conditions/LikeConditionBuilder.php
src/Query/Conditions/SimpleConditionBuilder.php
src/Query/Query.php
src/Query/QueryInterface.php
src/Schema/Schema.php
src/Schema/SchemaBuilderTrait.php
src/TestUtility/TestBatchQueryResultTrait.php
src/TestUtility/TestCommandTrait.php
src/TestUtility/TestConnectionTrait.php
src/TestUtility/TestQueryBuilderTrait.php
src/TestUtility/TestQueryTrait.php
src/TestUtility/TestSchemaTrait.php
src/TestUtility/TestSqlDataProviderTrait.php
src/TestUtility/TestTrait.php
src/Transaction/Transaction.php
tests/SortTest.php

| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.

Separate chain calls

---

src/Connection/ConnectionPoolInterface.php
src/Driver/PDO/ConnectionPDOPoolInterface.php

Split pool interface

---

src/Connection/Connection.php
src/Connection/ConnectionInterface.php
src/Query/BatchQueryResult.php
src/Query/BatchQueryResultInterface.php
src/Query/Query.php
src/Query/QueryInterface.php
src/TestSupport/TestBatchQueryResultTrait.php

Added interface for BatchQueryResult

---

src/QueryBuilder/DQLQueryBuilder.php

Fix for Param::class builder

---

src/Connection/ConnectionInterface.php
src/Connection/Dsn.php
src/Driver/PDO/ConnectionPDO.php
src/TestSupport/Provider/QueryBuilderProvider.php
src/TestSupport/TestCommandTrait.php
src/TestSupport/TestConnectionTrait.php
src/TestSupport/TestQueryBuilderTrait.php
src/TestSupport/TestQueryTrait.php

Add function getDriver co ConnectionPDOInterface

---

composer.json
src/TestSupport/TestCommandTrait.php

Add tests BatchInsert Fails.

---

composer.json

Add support for `yiisoft/cache` version `^2.0`

---

src/Command/Command.php
src/Command/CommandInterface.php
src/Query/Query.php
src/Query/QueryInterface.php
src/TestSupport/TestCommandTrait.php
src/TestSupport/TestQueryTrait.php

| Fixed issues  | #17 
Adopt PRs:
- https://github.com/yiisoft/active-record/pull/190
- https://github.com/yiisoft/db-mssql/pull/108
- https://github.com/yiisoft/db-mysql/pull/137
- https://github.com/yiisoft/db-oracle/pull/85
- https://github.com/yiisoft/db-pgsql/pull/140
- https://github.com/yiisoft/db-sqlite/pull/118

Change return type for query one and query column

---

src/Driver/PDO/PDODriver.php
src/Driver/PDO/PDODriverInterface.php

Change `chartset()` for `setCharset()`.

---

src/Schema/Quoter.php
src/Schema/QuoterInterface.php
src/Schema/Schema.php
src/Schema/TableSchema.php
src/Schema/TableSchemaInterface.php

Resolve table names. Parts 2

---

src/Schema/Quoter.php

Fix issue psalm.

---

src/Driver/PDO/ConnectionPDO.php
src/Schema/Quoter.php
src/TestSupport/TestSchemaTrait.php

Fixes for Quoter

---

src/Connection/ConnectionInterface.php
src/Driver/PDO/ConnectionPDO.php
src/Schema/Quoter.php
tests/QueryHelperTest.php

Fix for quoteValue

---

src/Cache/QueryCache.php
src/Cache/SchemaCache.php

Fix phpdoc directory `Cache`.

---

src/Command/Command.php
src/Command/CommandInterface.php
src/Driver/PDO/CommandPDO.php

Fix phpdoc directory `Command`.

---

src/Constraint/CheckConstraint.php
src/Constraint/Constraint.php
src/Constraint/ConstraintSchemaInterface.php
src/Constraint/DefaultValueConstraint.php
src/Constraint/ForeignKeyConstraint.php
src/Constraint/IndexConstraint.php

Fix phpdoc directory Constraint.

---

src/QueryBuilder/DMLQueryBuilder.php
src/Schema/Quoter.php
src/Schema/QuoterInterface.php
src/TestSupport/Provider/QueryBuilderProvider.php
src/TestSupport/TestCommandTrait.php

Refactoring of batchInsert (for remove using of Quoter)

---

src/Schema/Quoter.php
src/TestSupport/TestSchemaTrait.php
tests/QueryHelperTest.php

Remove connection from Quoter

---

src/Driver/PDO/ConnectionPDO.php
src/Schema/ColumnSchemaBuilder.php

Remove duplicate of code

---

.github/workflows/db-mysql.yml
src/Schema/ColumnSchemaBuilder.php
tests/Provider/ColumnTypes.php

Remove after and first (for alter columns)

---

tests/Common/CommonSchemaTest.php

Bugfix for PK in schema of Column

---

tests/Provider/AbstractQueryBuilderProvider.php

Add case for increase test cover

---

tests/QueryBuilder/QueryBuilderTest.php

Fix for cache in tests

---

src/QueryBuilder/DMLQueryBuilder.php
src/QueryBuilder/DMLQueryBuilderInterface.php
tests/Common/CommonCommandTest.php
tests/Provider/AbstractCommandProvider.php
tests/Provider/AbstractQueryBuilderProvider.php

Fix of normalize for column names in insert, batchInsert, upsert, update

---

src/Query/Query.php
tests/AbstractQueryTest.php
tests/Query/QueryTest.php

https://github.com/yiisoft/yii2/pull/17688

Add fix from yii2 https://github.com/yiisoft/yii2/pull/17688

---

src/Schema/QuoterInterface.php

Add attention to phpdoc

---

src/Command/ParamBuilder.php
src/QueryBuilder/QueryBuilder.php
tests/AbstractQueryBuilderTest.php

Fix for collisions in placeholders

---

composer.json
tests/AbstractQueryBuilderTest.php
tests/Provider/AbstractQueryBuilderProvider.php
tests/QueryBuilder/QueryBuilderTest.php

Improving test coverage - empty value in batchInsert

---

src/Command/Command.php
tests/Common/CommonCommandTest.php
tests/Provider/AbstractCommandProvider.php

Improve test coverage

---

src/QueryBuilder/DMLQueryBuilder.php
tests/Common/CommonCommandTest.php
tests/Provider/AbstractQueryBuilderProvider.php

Improve test coverage (prepareInsertSelectSubQuery)

---

src/Query/Helper/QueryHelper.php
tests/Query/Helper/QueryHelperTest.php

Improve test coverage for QueryHelper

---

src/QueryBuilder/DQLQueryBuilder.php
tests/AbstractQueryBuilderTest.php
tests/Common/CommonCommandTest.php

Improve test coverage for DataReader

---

tests/Common/CommonConnectionPDOTest.php
tests/Connection/ConnectionPDOTest.php

Improve test coverage for PDO Drivers

---

src/Command/CommandInterface.php
src/Driver/PDO/CommandPDO.php
src/QueryBuilder/DMLQueryBuilder.php
src/QueryBuilder/DMLQueryBuilderInterface.php
src/QueryBuilder/QueryBuilder.php
tests/AbstractQueryBuilderTest.php
tests/Common/CommonCommandTest.php
tests/Common/CommonSchemaTest.php
tests/Provider/AbstractQueryBuilderProvider.php
tests/QueryBuilder/QueryBuilderTest.php
tests/Support/Stub/Command.php

Add insertEx additional test + bugfix for oracle

---

src/Command/AbstractCommand.php
src/Driver/PDO/AbstractCommandPDO.php

Refactoring insertWithReturningPks

---

src/Command/AbstractCommand.php
src/Command/CommandInterface.php
src/Driver/PDO/AbstractCommandPDO.php
src/QueryBuilder/AbstractQueryBuilder.php
src/QueryBuilder/QueryBuilderInterface.php
tests/Common/CommonCommandPDOTest.php
tests/Common/CommonSchemaTest.php
tests/Provider/AbstractCommandProvider.php
tests/Provider/AbstractQueryBuilderProvider.php
tests/Provider/AbstractSchemaProvider.php

Work with constants QUERY_MODE & INDEX_UNIQUE

---

src/Command/AbstractCommand.php

Remove todo

---

composer.json
src/Command/AbstractCommand.php
src/Command/CommandInterface.php
src/Connection/AbstractConnection.php
src/Connection/ConnectionInterface.php
src/Profiler/ProfilerAwareTrait.php
src/Profiler/ProfilerInterface.php
tests/AbstractConnectionTest.php
tests/Common/CommonConnectionPDOTest.php
tests/Support/DbHelper.php

Removed dependency Yiisoft\Profiler

---

composer.json
src/Helper/NumericHelper.php
src/Schema/AbstractColumnSchema.php
src/Schema/AbstractColumnSchemaBuilder.php

Attempt to remove yiisoft/strings

---

composer.json
src/Helper/ArrayHelper.php
src/Query/Query.php
tests/AbstractQueryTest.php
tests/Helper/ArrayHelperTest.php

Attempt to remove of Yiisoft/Array depedency

---

src/Driver/PDO/AbstractCommandPDO.php
src/Driver/PDO/AbstractTransactionPDO.php
tests/Common/CommonCommandTest.php

Fixes from yii2. Part 1

---

src/Schema/AbstractColumnSchemaBuilder.php
src/Schema/ColumnSchemaBuilderInterface.php

- Reading for defaultValue in mssql
- Alter/drop column fix for MSSQL (https://github.com/yiisoft/yii2/pull/18136/)

Fixes for MSSQL

---

tests/AbstractConnectionPDOTest.php
tests/Common/CommonConnectionPDOTest.php
tests/Support/DbHelper.php

Logger mock

---

src/Schema/AbstractSchema.php

https://github.com/yiisoft/yii2/pull/18445

Remove brackets from MSSQL table names (in Schema)

---

src/Command/AbstractCommand.php
tests/AbstractConnectionTest.php
tests/Connection/ConnectionTest.php
tests/Provider/AbstractCommandProvider.php

https://github.com/yiisoft/yii2/pull/18592

Db Pgsql getRawSql params replace fix

---

src/Schema/AbstractColumnSchemaBuilder.php

https://github.com/yiisoft/yii2/pull/18617

MSSQL migration alterColumn on a column with default value NULL creates wrong CONSTRAINT

---

src/QueryBuilder/Condition/Builder/InConditionBuilder.php

Scrutinizer fixes (#18685)

---

src/Schema/Quoter.php

Mini fixes

---

src/QueryBuilder/Condition/Builder/InConditionBuilder.php
src/QueryBuilder/Condition/InCondition.php
src/QueryBuilder/Condition/Interface/InConditionInterface.php
tests/Provider/AbstractQueryBuilderProvider.php

https://github.com/yiisoft/yii2/pull/19152

Allow expression in IN builder for columns

---

src/Schema/AbstractSchema.php

Fix public->protected for internal const

---

tests/Common/CommonQueryBuilderTest.php
tests/Provider/ColumnTypes.php

| Fixed issues  | https://github.com/yiisoft/db-mysql/issues/224

Fix for type of boolean columns

---

src/Expression/JsonExpression.php
src/QueryBuilder/QueryBuilderInterface.php
src/Schema/AbstractColumnSchemaBuilder.php
src/Schema/SchemaInterface.php
tests/AbstractQueryBuilderTest.php
tests/AbstractQueryTest.php
tests/Common/CommonSchemaTest.php
tests/Provider/AbstractCommandProvider.php
tests/Provider/AbstractQueryBuilderProvider.php
tests/Provider/AbstractSchemaProvider.php

| Fixed issues  | https://github.com/yiisoft/db-mysql/issues/133

Const optimization

---

tests/AbstractCommandTest.php
tests/Command/CommandTest.php

Add test for Profiler

---

tests/Common/CommonCommandTest.php

Rename test testBatchInsertFailsOld

---

src/Schema/AbstractSchema.php
tests/Common/CommonCommandTest.php

| Fixed issues  | https://github.com/yiisoft/db/issues/264

Fix for typecast decimal columns

---

src/Query/Query.php
src/Schema/AbstractColumnSchema.php
src/Schema/AbstractColumnSchemaBuilder.php

Review (parts 2). Without folder QueryBuilder

---

src/QueryBuilder/Condition/BetweenColumnsCondition.php
src/QueryBuilder/Condition/BetweenCondition.php
src/QueryBuilder/Condition/Builder/NotConditionBuilder.php
src/QueryBuilder/Condition/Builder/SimpleConditionBuilder.php
src/QueryBuilder/Condition/ExistsCondition.php
src/QueryBuilder/Condition/InCondition.php
src/QueryBuilder/Condition/LikeCondition.php
src/QueryBuilder/Condition/NotCondition.php
src/QueryBuilder/Condition/SimpleCondition.php

QueryBuilder review: simple fixes + remove inversive logic

---

src/Schema/AbstractTableSchema.php
tests/Support/Stub/TableSchema.php

Add Abstract prefix for class TableSchema

---

tests/Common/CommonSchemaTest.php

Close connection in tests

---

src/Helper/StringHelper.php
src/Helper/UuidHelper.php
src/Schema/Builder/AbstractColumn.php
src/Schema/SchemaInterface.php
tests/Common/CommonColumnSchemaBuilderTest.php
tests/Db/Helper/UuidHelperTest.php
tests/Db/Schema/ColumnSchemaBuilderTest.php
tests/Provider/ColumnSchemaBuilderProvider.php

UUID PK support

---

src/Command/CommandInterface.php

phpdoc adjustments after reviewing CommandInterface.

CommandInterface phpdoc adjustments

---

src/Command/AbstractCommand.php
src/Command/CommandInterface.php

Move QUERY_MODE_* const to abstract classs and change private to protected

---

docs/en/command/ddl.md
src/Command/AbstractCommand.php
src/Command/CommandInterface.php
src/QueryBuilder/AbstractDDLQueryBuilder.php
src/QueryBuilder/AbstractQueryBuilder.php
src/QueryBuilder/DDLQueryBuilderInterface.php
tests/AbstractQueryBuilderTest.php
tests/Common/CommonCommandTest.php
tests/Common/CommonSchemaTest.php
tests/Db/Command/CommandTest.php
tests/Db/QueryBuilder/QueryBuilderTest.php
tests/Provider/QueryBuilderProvider.php

Change order of params in CommandInterface

---

composer.json

Prepare composer.json for release

---

src/Command/AbstractCommand.php
src/Command/CommandInterface.php
src/Connection/ConnectionInterface.php
src/Query/Query.php

Also changed `Query::addParam()` if structure to return early.

PHP Docs Improvements

---

src/Cache/SchemaCache.php
src/Schema/AbstractSchema.php
tests/Db/Cache/SchemaCacheTest.php

| Issue | https://github.com/yiisoft/db/issues/635

Remove cache duration `AbstractSchema::class`.

---

src/Query/Query.php
src/Query/QueryInterface.php
src/QueryBuilder/AbstractDQLQueryBuilder.php
tests/AbstractQueryTest.php

Remove unsed `Stringable` in `Query::class`.

---

docs/en/README.md
docs/en/connection/logger.md
docs/en/connection/mssql.md
docs/en/connection/mysql.md
docs/en/connection/oracle.md
docs/en/connection/pgsql.md
docs/en/connection/profiler.md
docs/en/connection/sqlite.md
docs/en/query-builder.md
docs/en/query/where.md

| Fixed issues  | Apply suggestion @arogachev docs.

Remove link package itself, adopt last change packages drivers.

---

docs/en/query/join.md

Apply corrections in notes.

---

docs/en/command/ddl.md
src/Schema/ColumnSchemaInterface.php
src/Schema/TableSchemaInterface.php

Various corrections before release, part 2

---

.gitignore
src/Cache/SchemaCache.php
src/Schema/AbstractSchema.php
src/Schema/SchemaInterface.php
tests/Common/CommonSchemaTest.php
tests/Db/Cache/SchemaCacheTest.php
tests/Db/Schema/SchemaTest.php

Fix #635: Simplify cache implementation

---

src/Query/Query.php
src/Query/QueryInterface.php
src/Query/QueryPartsInterface.php
src/QueryBuilder/AbstractDQLQueryBuilder.php
tests/AbstractQueryBuilderTest.php
tests/AbstractQueryTest.php

Fix #674: Correct union/join

---

docs/en/README.md
docs/en/queries/transactions.md

Document transactions

---

src/Cache/SchemaCache.php
src/Schema/AbstractSchema.php
tests/Db/Cache/SchemaCacheTest.php

Fix setter name

---

src/Constraint/ConstraintSchemaInterface.php
src/Schema/AbstractSchema.php
src/Schema/SchemaInterface.php

Fix issue psalm, remove unnecesary phpdoc.

---

docs/en/command/dml.md

Add example for insert to docs

---

UPGRADE.md
docs/en/README.md
docs/en/queries/transactions.md
src/Command/CommandInterface.php
src/Command/DataType.php
src/Connection/ConnectionInterface.php
src/Driver/Pdo/AbstractPdoCommand.php
src/Schema/AbstractColumnSchema.php
src/Schema/AbstractSchema.php
src/Schema/SchemaInterface.php
tests/AbstractQueryBuilderTest.php
tests/AbstractSchemaTest.php
tests/Db/Schema/ColumnSchemaTest.php
tests/Provider/CommandPDOProvider.php

Fix #692: Remove PDO from interfaces

---

docs/en/queries/create-command-fetch-data.md

wrong variable names passed in foreach block

---

docs/en/queries/transactions.md

Also added extra information about the error to the catch block

foreach loop should use list()

---

tests/Db/Schema/ColumnSchemaBuilderTest.php

Remove unneeded line from test

---

.github/workflows/db-mariadb.yml

Fix github actions for mariadb

---

CHANGELOG.md
src/Command/AbstractCommand.php
tests/Provider/CommandProvider.php

Fix `float` type in `AbstractCommand::getRawSql()`

---

CHANGELOG.md
UPGRADE.md
src/Driver/Pdo/AbstractPdoCommand.php

Remove `AbstractPdoCommand::logQuery()` method

---

.github/workflows/active-record.yml
.github/workflows/build.yml
.github/workflows/composer-require-checker.yml
.github/workflows/db-mariadb.yml
.github/workflows/db-mssql.yml
.github/workflows/db-mysql.yml
.github/workflows/db-oracle.yml
.github/workflows/db-pgsql.yml
.github/workflows/db-sqlite.yml
.github/workflows/rector.yml
.github/workflows/static.yml

Reduce tests running

---

.github/workflows/active-record.yml

Fix active-record tests

---

CHANGELOG.md
src/Schema/AbstractSchema.php
src/Schema/Column/BitColumnSchema.php
src/Schema/SchemaInterface.php
tests/Provider/ColumnSchemaProvider.php

- yiisoft/db-pgsql#353
- yiisoft/db-sqlite#312
- yiisoft/db-mysql#344
- yiisoft/db-mssql#312

Add `bit` abstract type

---

.github/workflows/active-record.yml
.github/workflows/build.yml
.github/workflows/db-mariadb.yml
.github/workflows/db-mssql.yml
.github/workflows/db-mysql.yml
.github/workflows/db-oracle.yml
.github/workflows/db-pgsql.yml
.github/workflows/db-sqlite.yml

Add display options to phpunit

---

.github/workflows/rector.yml
src/Schema/Quoter.php

Fix rector

---

.github/workflows/active-record.yml
.github/workflows/db-mssql.yml

- https://github.com/yiisoft/db-mssql/pull/323
- https://github.com/yiisoft/active-record/pull/389

Fix MSSQL tests

---

CHANGELOG.md
src/Connection/AbstractDsn.php

Related with https://github.com/yiisoft/db-mssql/pull/323

Refactor `AbstractDsn` class

---

CHANGELOG.md
src/QueryBuilder/AbstractDMLQueryBuilder.php
tests/Provider/QueryBuilderProvider.php
tests/Support/DbHelper.php

- https://github.com/yiisoft/db-oracle/pull/285
| Fixed issues  | yiisoft/db-oracle#284

Update DMLQueryBuilder::insertBatch() method

---

.github/workflows/active-record.yml
.github/workflows/db-migration.yml

Use only PHP 8.3 for testing `ActiveRecord` and `DbMigration`

---

CHANGELOG.md
src/Syntax/ColumnDefinitionParser.php
tests/Provider/ColumnDefinitionParserProvider.php

Parse comment from column definition

---

docs/internals.md

Actualize internal docs

---

tests/Provider/ColumnFactoryProvider.php

https://github.com/yiisoft/yii2/issues/20329

Add test for default value

---

CHANGELOG.md
src/Cache/SchemaCache.php
src/Command/AbstractCommand.php
src/Command/CommandInterface.php
src/Connection/AbstractConnection.php
src/Connection/ConnectionInterface.php
src/Debug/CommandInterfaceProxy.php
src/Debug/ConnectionInterfaceProxy.php
src/Debug/TransactionInterfaceDecorator.php
src/Driver/Pdo/AbstractPdoConnection.php
src/Driver/Pdo/AbstractPdoTransaction.php
src/Driver/Pdo/PdoConnectionInterface.php
src/Exception/Exception.php
src/Query/Query.php
src/Query/QueryPartsInterface.php
src/QueryBuilder/AbstractDDLQueryBuilder.php
src/QueryBuilder/AbstractDQLQueryBuilder.php
src/QueryBuilder/AbstractQueryBuilder.php
src/QueryBuilder/DDLQueryBuilderInterface.php
src/QueryBuilder/DQLQueryBuilderInterface.php
src/Transaction/TransactionInterface.php
tests/AbstractCommandTest.php
tests/Common/CommonSchemaTest.php
tests/Db/Command/CommandTest.php
tests/Support/Stub/Connection.php
tests/Support/Stub/Schema.php

- https://github.com/yiisoft/db-migration/pull/286
- https://github.com/yiisoft/db-pgsql/pull/387
- https://github.com/yiisoft/db-mssql/pull/343
- https://github.com/yiisoft/db-mysql/pull/377
- https://github.com/yiisoft/db-oracle/pull/305
- https://github.com/yiisoft/db-sqlite/pull/338

Explicitly mark nullable parameters

---

CHANGELOG.md
UPGRADE.md
composer.json
src/Cache/SchemaCache.php
src/Helper/DbStringHelper.php
tests/Db/Helper/DbStringHelperTest.php

- https://github.com/yiisoft/active-record/pull/405

Remove `ext-mbstring` from require section of `composer.json`

---

CHANGELOG.md
src/Schema/Column/IntegerColumn.php
src/Schema/Column/StringColumn.php
tests/Provider/ColumnProvider.php
tests/Support/IntEnum.php
tests/Support/StringEnum.php

Support PHP backed enums

---

CHANGELOG.md
src/Command/AbstractCommand.php
src/Command/CommandInterface.php
src/Query/Query.php
src/Query/QueryInterface.php

Improve typing of query result callback

---

CHANGELOG.md
UPGRADE.md
src/Query/Query.php
src/Query/QueryPartsInterface.php
tests/AbstractQueryBuilderTest.php

| Fixed issues  | https://github.com/yiisoft/db/issues/77

Added protection against accidental overwriting for the "->having()" method.

---

docs/guide/en/README.md
docs/guide/en/connection/mssql.md
docs/guide/en/connection/mysql.md
docs/guide/en/connection/oracle.md
docs/guide/en/connection/pgsql.md
docs/guide/en/connection/sqlite.md

Use more than one database connection

---

.github/workflows/db-mssql-2017.yml
.github/workflows/db-mssql.yml

Run MSSQL 2017 tests

---

CHANGELOG.md
UPGRADE.md
src/Query/Query.php
src/Query/QueryInterface.php
src/Query/QueryPartsInterface.php
src/QueryBuilder/AbstractDQLQueryBuilder.php
src/QueryBuilder/AbstractQueryBuilder.php
src/QueryBuilder/DQLQueryBuilderInterface.php
tests/AbstractQueryTest.php

Change in query "distinct" flag type from `bool|null` to `bool`

---

CHANGELOG.md
docs/guide/pt-BR/command/ddl.md
src/Command/CommandInterface.php
src/QueryBuilder/AbstractDDLQueryBuilder.php
src/QueryBuilder/DDLQueryBuilderInterface.php
tests/Db/Command/CommandTest.php
tests/Db/QueryBuilder/QueryBuilderTest.php

Allow `Expression` for column definitions when create table.

---

tests/Support/DbHelper.php

- https://github.com/yiisoft/db-sqlite/pull/362
- https://github.com/yiisoft/active-record/pull/430

Replace SQLite quotes from ` to "

---

CHANGELOG.md
UPGRADE.md
docs/guide/en/schema/typecasting.md
src/Command/AbstractCommand.php
src/Command/CommandInterface.php
src/Debug/CommandInterfaceProxy.php
src/Driver/Pdo/AbstractPdoCommand.php
src/QueryBuilder/AbstractDMLQueryBuilder.php
src/QueryBuilder/AbstractQueryBuilder.php
src/QueryBuilder/DMLQueryBuilderInterface.php
tests/AbstractQueryBuilderTest.php
tests/Common/CommonCommandTest.php
tests/Db/QueryBuilder/QueryBuilderTest.php
tests/Provider/QueryBuilderProvider.php

- https://github.com/yiisoft/db-sqlite/pull/361
- https://github.com/yiisoft/db-mysql/pull/399
- https://github.com/yiisoft/db-pgsql/pull/414
- https://github.com/yiisoft/db-mssql/pull/366
- https://github.com/yiisoft/db-oracle/pull/330
- https://github.com/yiisoft/active-record/pull/429

Rename `insertWithReturningPks()` to `insertReturningPks()`

---

CHANGELOG.md
UPGRADE.md
src/Connection/AbstractConnection.php
src/Connection/ConnectionInterface.php
src/Debug/ConnectionInterfaceProxy.php
tests/Db/Connection/ConnectionTest.php

Add `ConnectionInterface::select()` method

---

CHANGELOG.md
src/Debug/DatabaseCollector.php

Adapt to yiisoft/yii-debug summary

---

.github/workflows/active-record.yml
.github/workflows/composer-require-checker.yml
.github/workflows/db-mariadb.yml
.github/workflows/db-migration.yml
.github/workflows/db-mysql.yml
.github/workflows/db-oracle.yml
.github/workflows/db-pgsql.yml
.github/workflows/db-sqlite.yml
.github/workflows/rector.yml
.github/workflows/static.yml
rector.php

Refactor workflows

---

CHANGELOG.md
composer.json

Fix #698 
Related PRs:
- https://github.com/yiisoft/db-mssql/pull/372
- https://github.com/yiisoft/db-mysql/pull/405
- https://github.com/yiisoft/db-oracle/pull/336
- https://github.com/yiisoft/db-pgsql/pull/420
- https://github.com/yiisoft/db-sqlite/pull/368
- https://github.com/yiisoft/dummy-provider/pull/13

Introduce `yiisoft/db-implementation` virtual package

---

CHANGELOG.md
src/QueryBuilder/Condition/Builder/LikeBuilder.php
src/QueryBuilder/Condition/Like.php
src/QueryBuilder/Condition/LikeMode.php
tests/Db/QueryBuilder/Condition/Builder/LikeBuilderTest.php
tests/Db/QueryBuilder/Condition/LikeTest.php
tests/Provider/QueryBuilderProvider.php

Add mode parameter to `Like` condition

---

docker/Dockerfile

Fix docker base image

---

src/QueryBuilder/AbstractDQLQueryBuilder.php
src/QueryBuilder/Condition/AndX.php
src/QueryBuilder/Condition/OrX.php
tests/Db/QueryBuilder/Condition/AndXTest.php

Make `AndX`/`OrX` constructor parameter variadic

---

docker/docker-compose.yml

Mount psalm.xml to docker container

---

src/Expression/Value/Builder/DateTimeValueBuilder.php
src/Expression/Value/DateTimeValue.php

Suggestion for #1043

---

CHANGELOG.md
src/QueryBuilder/AbstractDMLQueryBuilder.php
tests/Common/CommonQueryBuilderTest.php
tests/Provider/QueryBuilderProvider.php

- https://github.com/yiisoft/db-sqlite/pull/389
- https://github.com/yiisoft/db-mysql/pull/426
- https://github.com/yiisoft/db-pgsql/pull/445
- https://github.com/yiisoft/db-mssql/pull/395
- https://github.com/yiisoft/db-oracle/pull/362

Upsert with multi-operand functions

---

docs/guide/en/expressions/expressions.md
docs/guide/en/expressions/values.md
docs/guide/en/query-builder.md
docs/guide/en/query-builder/building-queries.md

Update expressions doc

---

CHANGELOG.md
UPGRADE.md
src/Expression/Expression.php
src/Expression/ExpressionBuilder.php

Refactor `Expression` class

---

CHANGELOG.md
src/QueryBuilder/AbstractDQLQueryBuilder.php
tests/Db/QueryBuilder/QueryBuilderTest.php

Fix order of `FOR` clause in query
